[shell]
program = "/bin/zsh"
args = ["-l"]

[font]
normal = { family = "IntoneMono Nerd Font Mono", style = "Regular" }
bold = { family = "IntoneMono Nerd Font Mono", style = "Bold" }
italic = { family = "IntoneMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "IntoneMono Nerd Font Mono", style = "Bold Italic" }

[colors.primary]
background = "#000000"

[mouse]
hide_when_typing = true

[debug]
# render_timer = true
persistent_logging = true

